In [0]:
pip install pycountry_convert

In [0]:
from datascience import *
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

#Reading data from the file obtained from Q1
data_reader = Table.read_table('/content/sample_data/data_with_continents.csv')
data_reader = data_reader.relabeled('Country - HIV %','Country')

#converting to pandas data frame 
pandas_DF = data_reader.to_df()
#finding average of columns 2000 to 2011
pandas_DF['Avg 2000 to 2011']  = round(pandas_DF.iloc[:,23:35].mean(axis=1), 5)
#conerting back to Table
data_reader = Table.from_df(pandas_DF)

#Sorting Averages (in descending) based on continents
data_reader = (data_reader.sort('Avg 2000 to 2011',descending=True)).sort('Continents')
data_reader = data_reader.move_to_start('Avg 2000 to 2011')

#Selecting two tables with max & min averages for 2000 to 2011
cont_country_max = (data_reader.select(0,1,2)).group('Continents',max)
cont_country_min = (data_reader.select(0,1,2)).group('Continents',min)

#Joining the above max & min averages columns with the main table
data_reader = data_reader.join('Continents',cont_country_max).drop('Country max')
data_reader = data_reader.join('Continents',cont_country_min).drop('Country min')

#selecting columns with continents & country where the average is equal to max of averages for 2000 to 2011
cont_country_max = (data_reader.select('Continents','Avg 2000 to 2011','Country','Avg 2000 to 2011 max')).where('Avg 2000 to 2011',are.equal_to,'Avg 2000 to 2011 max')
cont_country_max = cont_country_max.drop('Avg 2000 to 2011 max')
cont_country_max.show()
print('\n')

#selecting columns with continents & country where the average is equal to min of averages for 2000 to 2011
cont_country_min = (data_reader.select('Continents','Avg 2000 to 2011','Country','Avg 2000 to 2011 min')).where('Avg 2000 to 2011',are.equal_to,'Avg 2000 to 2011 min')
cont_country_min = cont_country_min.drop('Avg 2000 to 2011 min')
cont_country_min.show()
print('\n')

#Plotting graphs for tables derived above
cont_country_max.barh('Continents','Avg 2000 to 2011')
print('\n')
cont_country_min.barh('Continents','Avg 2000 to 2011')
print('\n')

#Overlaid Bar Chart
cont_country_max = ((((cont_country_max.join('Continents',cont_country_min)).relabeled('Avg 2000 to 2011','Max Avg 2000 to 2011')).relabeled('Avg 2000 to 2011_2','Min Avg 2000 to 2011')).relabeled('Country_2','Min Country')).relabeled('Country','Max Country')
(cont_country_max.select('Continents','Max Avg 2000 to 2011','Min Avg 2000 to 2011')).barh('Continents')

#selecting country from each continent
SA = data_reader.where('Country',are.equal_to('South Africa')).drop("Continent",'Avg 2000 to 2011','1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999','Max Avg 2000 to 2011', 'Min Avg 2000 to 2011')
IND = data_reader.where('Country',are.equal_to('India')).drop("Continent",'Avg 2000 to 2011','1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999','Max Avg 2000 to 2011', 'Min Avg 2000 to 2011')
ENG = data_reader.where('Country',are.equal_to('United Kingdom')).drop("Continent",'Avg 2000 to 2011','1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999','Max Avg 2000 to 2011', 'Min Avg 2000 to 2011')
BAR = data_reader.where('Country',are.equal_to('Barbados')).drop("Continent",'Avg 2000 to 2011','1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999','Max Avg 2000 to 2011', 'Min Avg 2000 to 2011')
AUS = data_reader.where('Country',are.equal_to('Australia')).drop("Continent",'Avg 2000 to 2011','1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999','Max Avg 2000 to 2011', 'Min Avg 2000 to 2011')
BRA = data_reader.where('Country',are.equal_to('Brazil')).drop("Continent",'Avg 2000 to 2011','1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999','Max Avg 2000 to 2011', 'Min Avg 2000 to 2011')